project:
  type: website
  output-dir: docs

website:
  title: "kinderkamer"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true



